### ISSUE TITLE
Continue project to make an official HA integration?

### ISSUE THREAD

**Issue by ghost** [rgerganov/py-air-control#101]
Hey! I read your article on https://xakcop.com/post/ctrl-air-purifier/
Nice work! Could you make an official Home Assistant integration controlling the Philips Air Purifiers with coap protocol? Would be so great if someone did it... If not official then maye semi-official via HACS?

**Comment by kongo09** [comment]
quite a few people did. I've tried to build on that and currently maintain https://github.com/kongo09/philips-airpurifier-coap/

**Comment by ghost** [comment]
Why is it not in HACS?

**Comment by kongo09** [comment]
That is a very valid question and I guess it's just me being sloppy. I'll submit it later this week...
