### ISSUE TITLE
Night mode not supported

### ISSUE THREAD

**Issue by armageddon421** [rgerganov/py-air-control#13]
Hey There, awesome script and works perfectly for me, but it seems night mode is not selectable.
My device outputs the following, so N is for night mode:
`[pwr]   Power: ON
[pm25]  PM25: 34
[iaql]  Allergen index: 6
[mode]  Mode: N
[om]    Fan speed: 2
[aqil]  Light brightness: 0
[cl]    Child lock: False`

**Comment by rgerganov** [comment]
Thanks for the report. Which model is your purifier?

**Comment by armageddon421** [comment]
That would be an AC1214/10

**Comment by rgerganov** [comment]
I have added mode 'N' for night mode. Let me know if it works for you.

**Comment by armageddon421** [comment]
Sorry for the late reply. It's working perfectly, thanks!
