### ISSUE TITLE
Setting fan speed on AC2889 does not work

### ISSUE THREAD

**Issue by apfelsheriff** [rgerganov/py-air-control#16]
Hi Rgerganov,
First of all: Thanks for this great script and your effort to develop this!

I have two air purifiers in operation: The AC1214 and the AC2889.
The 1214 runs like a charm using your script.
For the 2889 the script works to change the mode and to power on/off. Unfortunately controlling the fan speed (the --om option) does not work. After sending the command, the status is left unchanged.

Here is the output of the --firmware option:
{'mandatory': False,
 'name': 'AC2889_10',
 'progress': 0,
 'state': 'idle',
 'statusmsg': '',
 'upgrade': '',
 'version': '14'}

Any idea about this? I would love to set the "turbo" fan option using the script.
By the way: I also have the error no. 193 after each command.

Thanks and keep on developing that,
Cheers, 
Holger

**Comment by crllo** [comment]
@apfelsheriff I also noticed this when I first used Rgerganov's script. However, this is just how AC2889 works. Just set it to manual mode first and then adjusting fan speed. It worked for me.

**Comment by apfelsheriff** [comment]
@crllo Thanks for this hint. How do I set the 2889 to manual mode? I can set it to auto, allergen or bacteria mode using the -- mode option with P, A or B as parameter. All others do not work.

Cheers, Holger

**Comment by crllo** [comment]
In my case --mode M works fine. Perhaps there are some firmware differences between our purifiers.

**Comment by apfelsheriff** [comment]
Just checked, it doesn't work for my device. Thanks anyway for assistance!

**Comment by rgerganov** [comment]
> By the way: I also have the error no. 193 after each command.

You can try running AirMatters and see if it shows what kind of error is this.

**Comment by apfelsheriff** [comment]
AirMatters doesn't show any error. (Or I don't know where I can find it within the app).

**Comment by slipstream1** [comment]
likewise i have the AC2889 and would like to set "sleep" fan speed but cant set any of the fan speeds - no matter what the mode selected, tried various combinations with no success

**Comment by hyphenc** [comment]
I have an AC2889 and setting the fan speed works fine when I also specify "Manual Mode" in the command, i.e.`airctrl $IP --mode M --om $FANSPEED`

**Comment by rgerganov** [comment]
@hyphenc thanks, I will put this info in the README file

**Comment by apfelsheriff** [comment]
@hyphenc: Thanks a lot. That works! :-)

**Comment by apfelsheriff** [comment]
solved.
