### ISSUE TITLE
How to acquire the device's IP after WiFi setup?

### ISSUE THREAD

**Issue by TchaikovDriver** [rgerganov/py-air-control#17]
Does the code provide a way to acquire the device's IP after WiFi setup? Didn't see any relative code. Is it possible to acquire that programmatically?

**Comment by rgerganov** [comment]
I am not aware of such method. After you specify the SSID and the password, the purifier gets its IP over DHCP. At least this is how mine works.

**Comment by TchaikovDriver** [comment]
> I am not aware of such method. After you specify the SSID and the password, the purifier gets its IP over DHCP. At least this is how mine works.

It seems that I can only fetch its IP from the router.  It's a pity that I can't integrate this project as well as getting device IP in an Android SDK.
Anyway, thanks for your reply.
