### ISSUE TITLE
File not found error after connecting to WiFi

### ISSUE THREAD

**Issue by michalboronski** [rgerganov/py-air-control#20]
Hi,
I have AC2889 and in my case all commands seems to work fine as long as I stay with the setup network (with ip 192.168.1.1). As soon as I execute command to switch to my home network, for all requests, all urls sent to AC I get 404. I tried with Postman app to send raw request :
`GET http://192.168.20.239/di/v1/products/1/air` gives me :
`File /di/v1/products/1/air not_found`

On the setup network I checked firmware with airctrl app :
```
{'mandatory': False,
 'name': 'AC2889_10',
 'progress': 0,
 'state': 'idle',
 'statusmsg': '',
 'upgrade': '',
 'version': '14'}
```

The key is stored properly in the file.
Any clue why it may happen? Anyone has same issue?

**Comment by rgerganov** [comment]
How do you switch to your home network? How do you find the IP address of the purifier after the switch?

**Comment by michalboronski** [comment]
Damm, that was it! I used wrong IP address from my network. I was pretty sure it was the one as the incorrect one was not visible until I switched the purifier to my home network. But it had to be some other device has accidentally appeared at the same time 🤦‍♂ . My bad! Thanks for the hint and sorry for troubling  :) Now all seems to work with the right IP

**Comment by rgerganov** [comment]
:+1:
