### ISSUE TITLE
API not accessible

### ISSUE THREAD

**Issue by tomaae** [rgerganov/py-air-control#22]
I just bought a new ac3858 and I'm getting this error:
>urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

> nmap -sT -p- 10.0.1.124
Starting Nmap 7.40 ( https://nmap.org ) at 2019-12-05 19:04 CET
Nmap scan report for 10.0.1.124
Host is up (0.036s latency).
All 65535 scanned ports on 10.0.1.124 are closed
MAC Address: B0:F8:93:92:27:62 (Shanghai Mxchip Information Technology)
Nmap done: 1 IP address (1 host up) scanned in 46.25 seconds

Am I missing something or does this mean philips blocked off their API? both air matters and clean home+ apps can connect to it without problem.

I have quickly checked what app does, but that port rejects curl and telnet, same as with all other ports
>2019-12-05 19:44:10.039488 IP (tos 0x0, ttl 241, id 24062, offset 0, flags [DF], proto TCP (6), length 40)
    ec2-54-93-218-6.eu-central-1.compute.amazonaws.com.8883 > 10.0.1.124.43069: Flags [.], cksum 0x42fe (correct), seq 2551543765, ack 30295, win 65475, length 0

**Comment by rgerganov** [comment]
Could you please follow issue #21 and try the steps I put there?

**Comment by tomaae** [comment]
I have same results, port 80 is closed. I'm not able to try your pairing method as I dont have wifi on pc.
I can capture packets if it helps, just tell me steps in air matters I should capture.

**Comment by rgerganov** [comment]
If you can capture any network traffic between AirMatters and your phone, it would be helpful.

**Comment by tomaae** [comment]
Sure. I turned off the purifier, force closed the app, reopened it, turned on the purifier via app and checked details in the app:
[ac3858.zip](https://github.com/rgerganov/py-air-control/files/3932193/ac3858.zip)

**Comment by tomaae** [comment]
btw, I have ssh access to my wifi, so if you need any details or specifics, its easy for me to capture anything.
I will probably not keep this model tho, its bit too loud for bedroom. Tho I dont know if I can get more silent one :(

**Comment by rgerganov** [comment]
In this packet dump there is TLS traffic between 10.0.1.124 and 54.93.218.6. Assuming that 10.0.1.124 is your phone, this means that AirMatters is not communicating with your purifier in the local network, but talks to some internet server (54.93.218.6). Are you sure that your phone is in the same local network as your purifier? If they are in the same local network, they should talk directly, not via internet.

**Comment by tomaae** [comment]
I'm on the same network, tested it with data disabled on my phone to be sure. 
10.0.1.124 is the purifier

I have disabled my internet port and this was the result:
![image](https://user-images.githubusercontent.com/23486452/70327844-fd4a6300-1837-11ea-8a7d-eddca0be3f0b.png)
Purifier is trying to connect to AWS server. Which probably means they will no longer be controllable locally and require uninterrupted internet access.

I tried to look if there are some firmware updates, but could not find anything. So its there is probably no change :(

**Comment by rgerganov** [comment]
> I'm on the same network, tested it with data disabled on my phone to be sure.
> 10.0.1.124 is the purifier

I am confused. If you disable the data on your phone **and** you are still able to control the purifier, this means that you are controlling the device locally. This is not the case in the packet dump that you provided.
The purifier always sends data to Philips servers, this is fine. We'd like to see the traffic between your phone and the purifier **in your local network**.

**Comment by tomaae** [comment]
No, it can still connect to internet over WiFi. 
Once I disable internet on my router, app is no longer able to connect to the purifier. 
There is no local traffic between phone and purifier. No tcp ports are open on purifier as shown in my first post. There could be udp opened, not sure.

**Comment by rgerganov** [comment]
Thanks for the information. Maybe they disabled the local interface on newer models. You can try putting the device into [pairing mode](https://github.com/rgerganov/py-air-control#wi-fi-setup) and see if there are any open ports then.

**Comment by tomaae** [comment]
I'm not able to do that. I dont have a computer with build-in wifi.

**Comment by rgerganov** [comment]
Can you check if the purifier has UDP port 1900 open and run the following commands (if you are on Linux):
```
$ sudo apt-get install gupnp-tools
$ gssdp-discover -i eth0 --timeout=3
```

**Comment by tomaae** [comment]
No, it reports bunch of devices, but nothing from the purifier.
I will be returning this device tomorrow and looking for different model tho.
