### ISSUE TITLE
Works with Philips AC1214/10

### ISSUE THREAD

**Issue by webosa** [rgerganov/py-air-control#24]
Thanks for your work! Verified that this works with the model AC 1214 also.

pi@RaspAssistant:~/py-air-control-master $ airctrl x.x.x.xxx --firmware
{'mandatory': False,
 'name': 'AC1214_10',
 'progress': 0,
 'state': 'idle',
 'statusmsg': '',
 'upgrade': '',
 'version': '2'}

[pwr]   Power: ON
[pm25]  PM25: 1
[iaql]  Allergen index: 1
[mode]  Mode: night
[om]    Fan speed: 1
[aqil]  Light brightness: 0
[uil]   Buttons light: OFF
[ddp]   Used index: PM2.5
[cl]    Child lock: False

**Comment by rgerganov** [comment]
Thanks for the report :)

**Comment by PieterGit** [comment]
I can also report success with COAP protocol and AC1214/10. It works with latest version and patched CoAPthon3 as discussed in https://github.com/rgerganov/py-air-control/issues/35#issuecomment-631899965

```
$ airctrl --ipaddr 192.168.x.y --protocol coap -d 
[name]                        Name: AirPurifier
[type]                        Type: AC1214
[modelid]                     ModelId: AC1214/10
[swversion]                   Version: 2.0.0
...
[ota]                         Over the air updates: no
...
[WifiVersion]                 WifiVersion: AWS_Philips_AIR@51.1
...
```
