### ISSUE TITLE
airctrl not working under Ubuntu

### ISSUE THREAD

**Issue by slodki** [rgerganov/py-air-control#27]
```
Traceback (most recent call last):
  File "./pyairctrl/airctrl.py", line 4, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
```

All [Debian](https://packages.debian.org/buster/amd64/python3-pycryptodome/filelist)/[Ubuntu](https://packages.ubuntu.com/eoan/amd64/python3-pycryptodome/filelist) packages install pycryptodome package under Cryptodome.

Solution:
Use [pycryptodomex](https://pypi.org/project/pycryptodomex/) to always use `Cryptodome` package name:
* change requirements.txt to `pycryptodomex>=3.4.7`
* change imports to `Cryptodome.Cipher import AES`

**Comment by rgerganov** [comment]
I guess I never hit this as I always use virtual environments and never install system wide packages. Anyway, I am fine switching to `pycryptodomex`.
