### ISSUE TITLE
Support for AC3039/10 (encrypted CoAP)

### ISSUE THREAD

**Issue by bobzomer** [rgerganov/py-air-control#36]
Hello,
I've got a brand new AC3039/10 which obviously use CoAP protocol, but data is encrypted. How could I make it work?
I attach a capture of communication between device and the Air Matters app. Do you think another capture of the wiki pairing could be of any help?
Thanks for your help.

[Capture_AC3039_10.pcap.gz](https://github.com/rgerganov/py-air-control/files/4535061/Capture_AC3039_10.pcap.gz)

**Comment by rgerganov** [comment]
You can follow issue #35, the guys there are making progress
