### ISSUE TITLE
Platform error fan.philips-airpurifier - No module named ‘Cryptodome’

### ISSUE THREAD

**Issue by ciumagcatalin** [rgerganov/py-air-control#38]
Hello,

I am trying to install it on my Home Assistant Core and I am getting the “Platform error fan.philips-airpurifier - No module named ‘Cryptodome’” error in the logs.
I tried to install pyCryptodome on the virtual env and it says "
Requirement already satisfied: pycryptodome in /srv/homeassistant/lib/python3.7/site-packages (3.9.7)".

Any ideas? I have the AC1214/10 model which I think needs the coap protocol.
I got the component from https://github.com/shexbeer/philips-airpurifier 7

Catalin

**Comment by rgerganov** [comment]
You have to install `pycryptodomex`, see `requirements.txt`
