### ISSUE TITLE
Does not work for AC1214/10

### ISSUE THREAD

**Issue by Blackpander** [rgerganov/py-air-control#45]
I just bought this air purifier but it does not work.

When i try to use airctrl it shows connection refused. And after I try to get the device id from the diagnostics email in air matters it show me certificate verification failed after running cloudctrl.

Has anybody have this model working? I am willing to test anything.

**Comment by rgerganov** [comment]
Have you tried both `http` and `coap` protocols?

**Comment by Blackpander** [comment]
If I use airctrl --ipaddr 192.168.1.*** --protocol coap then I get the error: airctrl: error: unrecognized arguments: --ipaddr --protocol coap

**Comment by rgerganov** [comment]
> Could it be that i'm using an old version, where these arguments are not in? I made a virtual environment en installed it trough `pip3 install py-air-control`

Yes, please install the latest code from Github with `python setup.py install`. You can still use virtual env.

**Comment by Blackpander** [comment]
Thank you, that worked! Coap it is :)
