### ISSUE TITLE
Cannot set all modes for AC2889

### ISSUE THREAD

**Issue by sidamos** [rgerganov/py-air-control#5]
The AC2889 has 3 modes: auto, allergen and bacteria.

The app reports the modes as "auto", "allergen" and "B".

When setting modes, the app allows "P", "A" and "S".

P switches to auto.
A switches to allergen.
S does nothing.

So, I cannot switch to bacteria mode with the app. Not a big deal for me, just wanted to report it.

Thanks!

**Comment by rgerganov** [comment]
Hi,
This is fixed with commit a11837c86. I will upload a new version on PyPI soon. Thanks!

**Comment by rgerganov** [comment]
I have released v0.0.3 which includes the fix for this issue

**Comment by sidamos** [comment]
0.0.3 still does nothing when I set mode S.

**Comment by rgerganov** [comment]
mode "S" works only on AC2729. Eventually we can have different set of options for every device but I prefer to keep it simple for now.

**Comment by sidamos** [comment]
OK, thank you!
