### ISSUE TITLE
no timeout when using CoAP

### ISSUE THREAD

**Issue by pythonbegginer** [rgerganov/py-air-control#60]
Could you add the exception, when CoAP protocol is used to pull information from air purifier in case when device is powered off or disconnected from network? At this moment when air purifier is not available, nothing is happening when query is sent, airctrl is working in background.
I'm using ACS2729/50. Below purifier is powered off, would be nice to receive any message when there is no answer after ~5sec. 
`[pezet@logsrv airpurifier]$ airctrl --ipaddr 192.168.10.253 --protocol coap
`

**Comment by rgerganov** [comment]
Added 5sec timeout
