### ISSUE TITLE
temporarily bricked AC1214/10

### ISSUE THREAD

**Issue by metebalci** [rgerganov/py-air-control#63]
I was trying to control an AC1214. It was working fine for some hours (I did get_status and set_values for pwr and om) but then it started to not work, the sync call in coap client was not working. Then I tried to control the device with the mobile app, and it was also not working. I tried putting the device into pairing mode, but I could not pair it with the official mobile app also.

I unplugged the device and waited a bit. Then I tried repairing with the mobile app again, and then it worked.

I think it might be a (negative) side-effect of using the API of the device like this.

**Comment by rgerganov** [comment]
Sorry to hear about that. I don't think you can permanently brick the device because that would be a critical security flaw for Philips.  If you manage to reproduce or find a workaround, PRs are welcome.

**Comment by metebalci** [comment]
No problem, I also think it should be impossible to do a permanent damage but it is still interesting this happened. This is exactly same as #58, so I am closing this issue.
