### ISSUE TITLE
Philips Air Purifier Services

### ISSUE THREAD

**Issue by wolfhond** [rgerganov/py-air-control#67]
Hello,

I have found the component of @shexbeer for the Philips Air Purifier.
And it works thanks a lot.

But I have seen it is a fork of xMrVizzy's component.  xMrVizzy his component has services for Fan Speed etc. 
(philips_airpurifier.set_mode)
But that component doesn't work because I need Protocol 3 CoAP.

Is there a way that I have also the service philips_airpurifier.set_mode.
Now I can only set te purifier on and off.

**Comment by rgerganov** [comment]
I don't know what kind of services you are talking about. This is a standalone CLI program for controlling air purifiers, see the README file.

**Comment by shexbeer** [comment]
Hi @wolfhond 
Please post your feature wishes over here please https://github.com/shexbeer/philips-airpurifier/issues
