### ISSUE TITLE
AC1214/10 Philips

### ISSUE THREAD

**Issue by stoyanland** [rgerganov/py-air-control#92]
22/06/2021, 17:01:04 [22.06.2021, 08:01:04] [Philips Air] [Living Room Purifier] Unable to get data for polling: Error: spawnSync python3 ETIMEDOUT.
22/06/2021, 17:01:04 [22.06.2021, 08:01:04] If your have "Error: spawnSync python3 ETIMEDOUT" your need unplug the accessory from outlet for 10 seconds and plug again.

If I make it after 1 min the same error. I am using coap portocol cuz, the http doesn't want to work for me.

**Comment by ThumbGen** [comment]
For

` airctrl --ipaddr 192.168.178.48 --protocol coap`

I get almost all the time (it works very rarely, 1 of 15-20 tries)

```
Unexpected error:'NoneType' object has no attribute 'payload'
Give up on message From None, To ('192.168.178.48', 5683), CON-2898, GET-None, [Uri-Path: sys, Uri-Path: dev, Uri-Path: status, Observe: 0, ] No payload

```

This happens since I've updated to  WifiVersion: AWS_Philips_AIR@64.3

**Comment by stoyanland** [comment]
Is it plug-in for WiFi option?
