### ISSUE TITLE
NameError: name 'urllib' is not defined

### ISSUE THREAD

**Issue by slachy** [rgerganov/py-air-control#96]
Hi, great work with this project! It is very useful for me.

In file airctrl.py:
There is a proper exception handling If set_value fails for some reason:
        except urllib.error.HTTPError as e:
            print("Error setting values (response code: {})".format(e.code))

But there is no 
import urllib
so there is a NameError on that line.

**Comment by rgerganov** [comment]
Thanks for the report, should be fixed now.
